"""clinical knowledge: condition_registry + drug_reference

Revision ID: 64f2074da7f6
Revises: 94cafa15d3a1
Create Date: 2026-08-14 15:11:09.582850

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '64f2074da7f6'
down_revision: str | None = '94cafa15d3a1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condition_registry',
    sa.Column('condition_code', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('aliases', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('engine_codes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_condition_registry_condition_code'), 'condition_registry', ['condition_code'], unique=True)
    op.create_table('drug_reference',
    sa.Column('source_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_normalized', sa.String(length=255), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('dosage_type', sa.String(length=64), nullable=True),
    sa.Column('pack_size', sa.String(length=128), nullable=True),
    sa.Column('price_inr', sa.Float(), nullable=True),
    sa.Column('is_discontinued', sa.Boolean(), nullable=False),
    sa.Column('composition1', sa.String(length=255), nullable=True),
    sa.Column('composition2', sa.String(length=255), nullable=True),
    sa.Column('composition_normalized', sa.String(length=512), nullable=True),
    sa.Column('side_effects', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('uses', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('substitutes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('chemical_class', sa.String(length=128), nullable=True),
    sa.Column('habit_forming', sa.String(length=16), nullable=True),
    sa.Column('therapeutic_class', sa.String(length=128), nullable=True),
    sa.Column('action_class', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_reference_composition_normalized'), 'drug_reference', ['composition_normalized'], unique=False)
    op.create_index(op.f('ix_drug_reference_name_normalized'), 'drug_reference', ['name_normalized'], unique=False)
    # (spurious sqlite-autogen embedding alter_column removed by hand)


def downgrade() -> None:
    op.drop_index(op.f('ix_drug_reference_name_normalized'), table_name='drug_reference')
    op.drop_index(op.f('ix_drug_reference_composition_normalized'), table_name='drug_reference')
    op.drop_table('drug_reference')
    op.drop_index(op.f('ix_condition_registry_condition_code'), table_name='condition_registry')
    op.drop_table('condition_registry')
    # ### end Alembic commands ###
